// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RepositoryLayer;
using System;

namespace RepositoryLayer.Migrations
{
    [DbContext(typeof(BDDContext))]
    [Migration("20220316095141_gestionStock")]
    partial class gestionStock
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("DomainLayer.Model.Article", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("artCatId");

                    b.Property<string>("designation");

                    b.Property<double>("prix");

                    b.Property<int>("quantity");

                    b.Property<string>("unity");

                    b.HasKey("id");

                    b.HasIndex("artCatId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("DomainLayer.Model.ArticleCategory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("categoryName");

                    b.Property<string>("description");

                    b.HasKey("id");

                    b.ToTable("ArticleCategories");
                });

            modelBuilder.Entity("DomainLayer.Model.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("description");

                    b.Property<string>("designation");

                    b.Property<double>("price");

                    b.HasKey("id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("DomainLayer.Model.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("personid");

                    b.HasKey("Id");

                    b.HasIndex("personid");

                    b.ToTable("client");
                });

            modelBuilder.Entity("DomainLayer.Model.Input", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("artId");

                    b.Property<DateTime>("dateEntree");

                    b.Property<double>("prixEntree");

                    b.Property<int>("quantity");

                    b.HasKey("id");

                    b.HasIndex("artId");

                    b.ToTable("Inputs");
                });

            modelBuilder.Entity("DomainLayer.Model.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dateCommande");

                    b.Property<int>("ordlineId");

                    b.Property<string>("state");

                    b.HasKey("id");

                    b.HasIndex("ordlineId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DomainLayer.Model.OrderLine", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("amount");

                    b.Property<int>("artId");

                    b.Property<double>("price");

                    b.Property<int>("qtCommander");

                    b.HasKey("id");

                    b.HasIndex("artId");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("DomainLayer.Model.Output", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("artId");

                    b.Property<DateTime>("dateSortie");

                    b.Property<double>("prixSortie");

                    b.Property<int>("quantity");

                    b.HasKey("id");

                    b.HasIndex("artId");

                    b.ToTable("Outputs");
                });

            modelBuilder.Entity("DomainLayer.Model.Person", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CIN");

                    b.Property<string>("firstName");

                    b.Property<string>("lastName");

                    b.Property<string>("phone");

                    b.HasKey("id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("DomainLayer.Model.Reception", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dateReception");

                    b.Property<int>("ordId");

                    b.Property<int>("qtLivrer");

                    b.HasKey("id");

                    b.HasIndex("ordId");

                    b.ToTable("Receptions");
                });

            modelBuilder.Entity("DomainLayer.Model.Reservation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("NbrPerson");

                    b.Property<int?>("clientId");

                    b.Property<DateTime>("dateDebut");

                    b.Property<DateTime>("dateFin");

                    b.Property<DateTime>("dateReservation");

                    b.Property<int?>("roomnumber");

                    b.HasKey("id");

                    b.HasIndex("clientId");

                    b.HasIndex("roomnumber");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("DomainLayer.Model.Room", b =>
                {
                    b.Property<int>("number")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("categoryid");

                    b.Property<double>("price");

                    b.Property<string>("type");

                    b.HasKey("number");

                    b.HasIndex("categoryid");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("DomainLayer.Model.Supplier", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("adress");

                    b.Property<int>("codePost");

                    b.Property<string>("email");

                    b.Property<string>("phone");

                    b.Property<string>("supplierName");

                    b.HasKey("id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("DomainLayer.Model.Article", b =>
                {
                    b.HasOne("DomainLayer.Model.ArticleCategory", "artCat")
                        .WithMany()
                        .HasForeignKey("artCatId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainLayer.Model.Client", b =>
                {
                    b.HasOne("DomainLayer.Model.Person", "person")
                        .WithMany()
                        .HasForeignKey("personid");
                });

            modelBuilder.Entity("DomainLayer.Model.Input", b =>
                {
                    b.HasOne("DomainLayer.Model.Article", "art")
                        .WithMany()
                        .HasForeignKey("artId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainLayer.Model.Order", b =>
                {
                    b.HasOne("DomainLayer.Model.OrderLine", "ordline")
                        .WithMany()
                        .HasForeignKey("ordlineId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainLayer.Model.OrderLine", b =>
                {
                    b.HasOne("DomainLayer.Model.Article", "art")
                        .WithMany()
                        .HasForeignKey("artId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainLayer.Model.Output", b =>
                {
                    b.HasOne("DomainLayer.Model.Article", "art")
                        .WithMany()
                        .HasForeignKey("artId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainLayer.Model.Reception", b =>
                {
                    b.HasOne("DomainLayer.Model.Order", "ord")
                        .WithMany()
                        .HasForeignKey("ordId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainLayer.Model.Reservation", b =>
                {
                    b.HasOne("DomainLayer.Model.Client", "client")
                        .WithMany()
                        .HasForeignKey("clientId");

                    b.HasOne("DomainLayer.Model.Room", "room")
                        .WithMany()
                        .HasForeignKey("roomnumber");
                });

            modelBuilder.Entity("DomainLayer.Model.Room", b =>
                {
                    b.HasOne("DomainLayer.Model.Category", "category")
                        .WithMany()
                        .HasForeignKey("categoryid");
                });
#pragma warning restore 612, 618
        }
    }
}
