// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RepositoryLayer;
using System;

namespace RepositoryLayer.Migrations
{
    [DbContext(typeof(BDDContext))]
    partial class BDDContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("DomainLayer.Model.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("description");

                    b.Property<string>("designation");

                    b.Property<double>("price");

                    b.HasKey("id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("DomainLayer.Model.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("personid");

                    b.HasKey("Id");

                    b.HasIndex("personid");

                    b.ToTable("client");
                });

            modelBuilder.Entity("DomainLayer.Model.Person", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CIN");

                    b.Property<string>("firstName");

                    b.Property<string>("lastName");

                    b.Property<string>("phone");

                    b.HasKey("id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("DomainLayer.Model.Reservation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("NbrPerson");

                    b.Property<int?>("clientId");

                    b.Property<DateTime>("dateDebut");

                    b.Property<DateTime>("dateFin");

                    b.Property<DateTime>("dateReservation");

                    b.Property<int?>("roomnumber");

                    b.HasKey("id");

                    b.HasIndex("clientId");

                    b.HasIndex("roomnumber");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("DomainLayer.Model.Room", b =>
                {
                    b.Property<int>("number")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("categoryid");

                    b.Property<string>("type");

                    b.HasKey("number");

                    b.HasIndex("categoryid");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("DomainLayer.Model.Client", b =>
                {
                    b.HasOne("DomainLayer.Model.Person", "person")
                        .WithMany()
                        .HasForeignKey("personid");
                });

            modelBuilder.Entity("DomainLayer.Model.Reservation", b =>
                {
                    b.HasOne("DomainLayer.Model.Client", "client")
                        .WithMany()
                        .HasForeignKey("clientId");

                    b.HasOne("DomainLayer.Model.Room", "room")
                        .WithMany()
                        .HasForeignKey("roomnumber");
                });

            modelBuilder.Entity("DomainLayer.Model.Room", b =>
                {
                    b.HasOne("DomainLayer.Model.Category", "category")
                        .WithMany()
                        .HasForeignKey("categoryid");
                });
#pragma warning restore 612, 618
        }
    }
}
